// Sample recipe database for RAG system
export const sampleRecipes = [
  // Indian Vegetarian
  {
    id: "veg_paneer_tikka",
    name: "Paneer Tikka",
    cuisine: "Indian",
    vegetarian: true,
    calories: 250,
    protein: 15,
    carbs: 8,
    fats: 18,
    allergies: ["dairy"],
    description:
      "Grilled paneer cubes marinated in yogurt and spices, high protein vegetarian option",
    ingredients: ["paneer", "yogurt", "ginger", "garlic", "spices"],
  },
  {
    id: "veg_dal_rice",
    name: "Dal with Brown Rice",
    cuisine: "Indian",
    vegetarian: true,
    calories: 350,
    protein: 12,
    carbs: 52,
    fats: 4,
    allergies: [],
    description:
      "Protein-rich lentils cooked with cumin and turmeric, served with brown rice",
    ingredients: ["lentils", "rice", "cumin", "turmeric", "onion"],
  },
  {
    id: "veg_chikpea_curry",
    name: "Chickpea Curry",
    cuisine: "Indian",
    vegetarian: true,
    calories: 280,
    protein: 11,
    carbs: 38,
    fats: 7,
    allergies: [],
    description:
      "Chickpeas in tomato-based curry, rich in fiber and plant protein",
    ingredients: ["chickpeas", "tomato", "onion", "garlic", "coconut milk"],
  },
  {
    id: "veg_aloo_gobi",
    name: "Aloo Gobi",
    cuisine: "Indian",
    vegetarian: true,
    calories: 180,
    protein: 6,
    carbs: 28,
    fats: 5,
    allergies: [],
    description:
      "Potato and cauliflower dry curry with minimal oil, light and nutritious",
    ingredients: ["potato", "cauliflower", "turmeric", "cumin", "onion"],
  },
  {
    id: "veg_veggie_dosa",
    name: "Vegetable Dosa",
    cuisine: "Indian",
    vegetarian: true,
    calories: 220,
    protein: 8,
    carbs: 32,
    fats: 6,
    allergies: [],
    description:
      "Crispy fermented rice and lentil crepe with vegetable filling",
    ingredients: ["rice flour", "urad dal", "potato", "onion", "vegetables"],
  },

  // Indian Non-Vegetarian
  {
    id: "nonveg_chicken_tikka",
    name: "Chicken Tikka",
    cuisine: "Indian",
    vegetarian: false,
    calories: 280,
    protein: 35,
    carbs: 5,
    fats: 12,
    allergies: ["poultry"],
    description:
      "Grilled chicken pieces marinated in yogurt and spices, high protein",
    ingredients: ["chicken breast", "yogurt", "ginger", "garlic", "spices"],
  },
  {
    id: "nonveg_fish_curry",
    name: "Fish Curry",
    cuisine: "Indian",
    vegetarian: false,
    calories: 250,
    protein: 32,
    carbs: 6,
    fats: 10,
    allergies: ["fish"],
    description: "Salmon or cod in coconut curry, rich omega-3 source",
    ingredients: ["fish", "coconut milk", "tomato", "onion", "turmeric"],
  },
  {
    id: "nonveg_mutton_biryani",
    name: "Mutton Biryani",
    cuisine: "Indian",
    vegetarian: false,
    calories: 420,
    protein: 28,
    carbs: 48,
    fats: 14,
    allergies: ["meat"],
    description:
      "Fragrant basmati rice with slow-cooked mutton, aromatic spices",
    ingredients: ["mutton", "basmati rice", "yogurt", "spices", "mint"],
  },
  {
    id: "nonveg_butter_chicken",
    name: "Butter Chicken",
    cuisine: "Indian",
    vegetarian: false,
    calories: 380,
    protein: 32,
    carbs: 18,
    fats: 22,
    allergies: ["poultry", "dairy"],
    description: "Tender chicken in creamy tomato sauce with butter and cream",
    ingredients: ["chicken", "butter", "cream", "tomato", "spices"],
  },

  // Mediterranean
  {
    id: "med_grilled_fish",
    name: "Grilled Mediterranean Fish",
    cuisine: "Mediterranean",
    vegetarian: false,
    calories: 320,
    protein: 38,
    carbs: 8,
    fats: 14,
    allergies: ["fish"],
    description: "White fish grilled with olive oil, lemon, and herbs",
    ingredients: ["white fish", "olive oil", "lemon", "herbs", "garlic"],
  },
  {
    id: "med_greek_salad",
    name: "Greek Salad",
    cuisine: "Mediterranean",
    vegetarian: true,
    calories: 280,
    protein: 8,
    carbs: 18,
    fats: 20,
    allergies: ["dairy"],
    description: "Fresh vegetables with feta cheese and olive oil dressing",
    ingredients: ["tomato", "cucumber", "feta", "olives", "olive oil"],
  },
  {
    id: "med_hummus_plate",
    name: "Hummus with Vegetables",
    cuisine: "Mediterranean",
    vegetarian: true,
    calories: 240,
    protein: 8,
    carbs: 24,
    fats: 12,
    allergies: ["sesame"],
    description:
      "Chickpea hummus with fresh vegetable sticks, protein-rich snack",
    ingredients: ["chickpeas", "tahini", "lemon", "vegetables", "olive oil"],
  },

  // Asian
  {
    id: "asian_chicken_stir_fry",
    name: "Chicken Stir Fry",
    cuisine: "Asian",
    vegetarian: false,
    calories: 310,
    protein: 34,
    carbs: 20,
    fats: 11,
    allergies: ["poultry", "soy"],
    description: "Lean chicken with colorful vegetables and soy sauce",
    ingredients: [
      "chicken breast",
      "bell peppers",
      "broccoli",
      "soy sauce",
      "garlic",
    ],
  },
  {
    id: "asian_veggie_stir_fry",
    name: "Vegetable Stir Fry",
    cuisine: "Asian",
    vegetarian: true,
    calories: 200,
    protein: 8,
    carbs: 28,
    fats: 7,
    allergies: ["soy"],
    description: "Mixed vegetables with soy sauce and sesame oil",
    ingredients: ["vegetables", "soy sauce", "sesame oil", "garlic", "ginger"],
  },
  {
    id: "asian_tofu_curry",
    name: "Thai Tofu Curry",
    cuisine: "Asian",
    vegetarian: true,
    calories: 280,
    protein: 16,
    carbs: 16,
    fats: 18,
    allergies: ["soy", "coconut"],
    description: "Silken tofu in spicy coconut curry sauce",
    ingredients: ["tofu", "coconut milk", "curry paste", "vegetables", "lime"],
  },

  // Mexican
  {
    id: "mex_chicken_tacos",
    name: "Grilled Chicken Tacos",
    cuisine: "Mexican",
    vegetarian: false,
    calories: 320,
    protein: 32,
    carbs: 28,
    fats: 10,
    allergies: ["poultry", "gluten"],
    description:
      "Seasoned chicken with whole wheat tortillas and fresh toppings",
    ingredients: ["chicken", "tortillas", "lettuce", "tomato", "salsa"],
  },
  {
    id: "mex_black_bean_bowl",
    name: "Black Bean & Quinoa Bowl",
    cuisine: "Mexican",
    vegetarian: true,
    calories: 340,
    protein: 14,
    carbs: 48,
    fats: 8,
    allergies: [],
    description:
      "Protein-rich black beans with quinoa, complete amino acid profile",
    ingredients: ["black beans", "quinoa", "corn", "bell pepper", "avocado"],
  },

  // Thai
  {
    id: "thai_shrimp_pad_thai",
    name: "Shrimp Pad Thai",
    cuisine: "Thai",
    vegetarian: false,
    calories: 380,
    protein: 28,
    carbs: 42,
    fats: 12,
    allergies: ["shellfish", "peanuts"],
    description: "Rice noodles with shrimp, eggs, and tamarind sauce",
    ingredients: ["shrimp", "noodles", "egg", "tamarind", "peanuts"],
  },
  {
    id: "thai_green_curry",
    name: "Green Curry Vegetables",
    cuisine: "Thai",
    vegetarian: true,
    calories: 240,
    protein: 8,
    carbs: 18,
    fats: 16,
    allergies: ["coconut"],
    description: "Mixed vegetables in spicy green curry sauce",
    ingredients: ["vegetables", "coconut milk", "curry paste", "basil", "lime"],
  },

  // Italian
  {
    id: "ital_grilled_salmon",
    name: "Grilled Salmon with Herbs",
    cuisine: "Italian",
    vegetarian: false,
    calories: 350,
    protein: 38,
    carbs: 0,
    fats: 20,
    allergies: ["fish"],
    description: "Salmon fillet with Italian herbs, rich in omega-3",
    ingredients: ["salmon", "olive oil", "herbs", "lemon", "garlic"],
  },
  {
    id: "ital_vegetable_pasta",
    name: "Whole Wheat Pasta Primavera",
    cuisine: "Italian",
    vegetarian: true,
    calories: 360,
    protein: 13,
    carbs: 52,
    fats: 10,
    allergies: ["gluten"],
    description: "Whole grain pasta with seasonal vegetables and olive oil",
    ingredients: [
      "whole wheat pasta",
      "vegetables",
      "olive oil",
      "garlic",
      "herbs",
    ],
  },

  // Healthy Breakfast Options
  {
    id: "breakfast_oats",
    name: "Protein Oatmeal",
    cuisine: "International",
    vegetarian: true,
    calories: 280,
    protein: 12,
    carbs: 42,
    fats: 6,
    allergies: ["gluten"],
    description:
      "Rolled oats with milk, honey, and nuts, sustained energy release",
    ingredients: ["oats", "milk", "honey", "nuts", "berries"],
  },
  {
    id: "breakfast_eggs",
    name: "Scrambled Eggs with Toast",
    cuisine: "International",
    vegetarian: true,
    calories: 320,
    protein: 18,
    carbs: 28,
    fats: 14,
    allergies: ["gluten", "eggs"],
    description: "Protein-rich breakfast with whole grain toast",
    ingredients: ["eggs", "bread", "butter", "vegetables", "salt"],
  },
  {
    id: "breakfast_smoothie",
    name: "Protein Smoothie",
    cuisine: "International",
    vegetarian: true,
    calories: 240,
    protein: 20,
    carbs: 32,
    fats: 4,
    allergies: ["dairy", "nuts"],
    description: "Fruit and protein powder smoothie, quick meal",
    ingredients: ["yogurt", "fruit", "protein powder", "milk", "honey"],
  },

  // Healthy Snacks
  {
    id: "snack_almonds",
    name: "Almonds & Berries",
    cuisine: "International",
    vegetarian: true,
    calories: 180,
    protein: 6,
    carbs: 14,
    fats: 12,
    allergies: ["nuts"],
    description: "Nuts and fresh berries for sustained energy",
    ingredients: ["almonds", "berries", "water"],
  },
  {
    id: "snack_fruit",
    name: "Fresh Apple with Peanut Butter",
    cuisine: "International",
    vegetarian: true,
    calories: 200,
    protein: 7,
    carbs: 24,
    fats: 9,
    allergies: ["peanuts"],
    description: "Natural sweetness with protein-rich peanut butter",
    ingredients: ["apple", "peanut butter", "honey"],
  },
];

// Initialize recipes on startup
export const initializeRecipeDatabase = async () => {
  console.log(`📚 Recipe database loaded with ${sampleRecipes.length} recipes`);
  return sampleRecipes;
};
